[package]
name = "mc-ping"
version = "0.1.0"
authors = ["Aurora <tomek-kubel2@wp.pl>"]
edition = "2018"

[dependencies]
structopt = "0.2.15"
serde = { version = "1.0.91", features = ["derive"] }
serde_json = "1.0.39"